<user nick="othermaciej" alias="othermaciej_ om_out om_meet om_sleep">
<user nick="MacDome" alias="MacDomeAFK MacDomeSleep MacDome_ MacDomeRuby MacDomePack">
<user nick="dhyatt" alias="hyatt">
<user nick="cheers" alias="cheers_">
<user nick="olliej" alias="olliej_">
<user nick="lars" alias="lars|home">
<user nick="andersca" alias="andersca_">
<user nick="xenon" alias="xenon_ nonex">
<user nick="darin" alias="darin_ darinMeet">
<user nick="mitz" alias="mitzpettel mitz|away">
<user nick="weinig" alias="sweinig">
<user nick="tcooper" alias="tcooper_">
<user nick="bradee-oh" alias="bradee-oh_ home_bradee home-bradee">
<user nick="ddkilzer" alias="ddk|afk">
<user nick="lypanov" alias="lypanov_ lyp|code">
<user nick="dacarson" alias="dacarson_">
<user nick="ggaren" alias="ggaren_">
<user nick="wildfox" alias="wild|zzz wild|brb wild|away Wild|TV">
<user nick="rwlbuis" alias="rwlbuis|bbl">
<user nick="rtyler" alias="rtyler|intel">
<user nick="CIA" alias="CIA-1 CIA-5 CIA-27 CIA-10 CIA-19 CIA-6 CIA-22 CIA-7 CIA-2 CIA-18 CIA-4 CIA-17 CIA-12">
<user nick="zecke" alias="zecke_">
<user nick="kollivier" alias="kollivier_">
<user nick="seb_" alias="_seb">
