<user nick="othermaciej" alias="othermacie othermaciej_ om_out om_meet om_sleep mjs">
<user nick="eseidel" alias="MacDomeAFK MacDomeSleep MacDome_ MacDomeRuby MacDomePack MacDome eseidel_">
<user nick="Catfish_Man" alias="Catfish">
<user nick="dhyatt" alias="hyatt">
<user nick="cheers" alias="cheers_">
<user nick="olliej" alias="olliej_ olliej|pirate fakeolliej">
<user nick="lars" alias="lars|home">
<user nick="andersca" alias="andersca_">
<user nick="xenon" alias="xenon_ nonex">
<user nick="darin" alias="darin_ darinMeet">
<user nick="mitz" alias="mitzpettel mitz|away">
<user nick="weinig" alias="sweinig weinig_ weinigLap">
<user nick="tcooper" alias="tcooper_">
<user nick="bradee-oh" alias="bradee-oh_ home_bradee home-bradee">
<user nick="ddkilzer" alias="ddk|afk">
<user nick="lypanov" alias="lypanov_ lyp|code">
<user nick="dacarson" alias="dacarson_">
<user nick="ggaren" alias="ggaren_">
<user nick="wildfox" alias="wild|zzz wild|brb wild|away Wild|TV">
<user nick="rwlbuis" alias="rwlbuis|bbl rwlbuis|work">
<user nick="rtyler" alias="rtyler|intel">
<user nick="CIA" alias="CIA\-\d+">
<user nick="zecke" alias="zecke_">
<user nick="kollivier" alias="kollivier_">
<user nick="seb_" alias="_seb">
<user nick="AngryLuke" alias="AngryLuke_ICBM">
<user nick="aroben" alias="aroben_">
<user nick="kalikiana" alias="kalikiana_">
<user nick="jeremyb" alias="jeremyb_">
<user nick="joshmoz" alias="joshmoz_">
<user nick="bfulgham" alias="bfulgham_">
<user nick="MachinaX^4" alias="MachinaX^4_">
