<user nick="gavin" alias="g gavin* sharpg gav">
<user nick="timeless" alias="proxyvictim timely* timele* wounded_monkey compiledmonkey proxy_monkey spidercrasher chistery chistery_ iunknown sslmonkey">
<user nick="bz" alias="bz_* bzbarsky">
<user nick="biesi" alias="biesi*">
<user nick="smaug" alias="smaug*">
<user nick="cbarrett" alias="cbarrett*">
<user nick="stephend" alias="stephend*">
<user nick="raccettura" alias="DIGITALgimpus">
<user nick="Jesse" alias="Jesse_* Jesse|*">
<user nick="jst" alias="jst*">
<user nick="mcsmurf" alias="mcsmurf_">
<user nick="wormsxulla" alias="worms_* wormszilla worm_invasion wormxulla worms979 sideworms wormsworms emoxulla roquette wx2la bunnyzilla">
<user nick="Mardak" alias="Mardak_">
<user nick="mystic" alias="mystic_* mystic|*">
<user nick="dveditz" alias="dveditz_ dveditz2">
<user nick="poningru" alias="poningru_* Capt_Blood_Poningru tipsy_poningru">
<user nick="reed" alias="reed[*] [reed] reed_* reed^pirateguy reed2 reed-* reed|* ]reed[">
<user nick="ss" alias="ss|* Capn-Black-Sam samuelsidler* ssreed ss_ ss2 DreadPirateSam">
<user nick="Lucy" alias="Lucy|* Lucy_* mrsconnor Commodore_Black_Lucy LucyPurpleHair CptnBlackLucy">
<user nick="stuart" alias="Pavlov pav stuart_*">
<user nick="nthomas" alias="nthomas|* nthomas-* nthomas_* cf cf2 cf_* cf-* cf|*">
<user nick="olliej" alias="olliej_* fakeolliej">
<user nick="Mano" alias="Mano*">
<user nick="Mook" alias="Mook_sb">
<user nick="chesh" alias="chesh|away">
<user nick="aconbere" alias="aconbere|* aconbere_*">
<user nick="bsmedberg" alias="csmedberg bsmedberg-* dsmedberg">
<user nick="doron" alias="doronHome doron_*">
<user nick="preed" alias="preed-* preedMsgMe notpreed">
<user nick="rhelmer" alias="rhelmer-* rhelmer|*">
<user nick="pkasting" alias="pkasting_*">
<user nick="tor" alias="tor_*">
<user nick="Waldo" alias="Waldo|* jwalden">
<user nick="philor" alias="philor_*">
<user nick="Neil" alias="NeilAway NeilZZZ NeilZZZ_* NeilAlmostZZZ NeilLinux">
<user nick="CTho" alias="CTho|* CTho_*">
<user nick="Ryan" alias="Ryan|* Ryan_* First_Mate_Puddles rflint">
<user nick="kbrosnan" alias="kb|* brosnan Cpt_O|Malley_brosnan">
<user nick="Yoric" alias="oYoric mYoric">
<user nick="dietrich" alias="dietrich_* autonome">
<user nick="Peter6" alias="Peter6_*">
<user nick="ispiked" alias="ispiked_*">
<user nick="Wolf" alias="NotWolf Wolf|* X-Wolf Wolf_*">
<user nick="mconnor" alias="mconnor|* mconnor_* mconnorrrrr">
<user nick="dmiller" alias="dmiller|away">
<user nick="jhughes" alias="jhughes_">
<user nick="firebot" alias="firewolfbot altfirebot notfirebot">
<user nick="foxbot" alias="FoxBot foxbot2">
<user nick="beltzner" alias="beltzner|* beltzner_*">
<user nick="markp" alias="markp_">
<user nick="Mossop" alias="Mossop_* Mossop2 Mosssop">
<user nick="dolske" alias="dolske|* dolske_* DreadCaptainDolske">
<user nick="pkim" alias="pkim_">
<user nick="jminta" alias="jmacminta jminta_">
<user nick="aaronlev" alias="aaronlufthansa aaronl aaronbeer">
<user nick="sayrer" alias="sayyaaaar sayrer_* sayre1">
<user nick="bhearsum" alias="Cpt_Beer_Some bhearsum|*">
<user nick="morgamic" alias="morgamic|*">
<user nick="zach" alias="zach_* zach-*">
<user nick="Cameron" alias="Cameron|*">
<user nick="klock" alias="klock_">
<user nick="schrep" alias="schrep_*">
<user nick="johnath" alias="Johnath johnath_* johnath|*">
<user nick="lilmatt" alias="lilmatt_">
<user nick="sp3000" alias="sp3k sp300*">
<user nick="redfive" alias="redfive_*">
<user nick="ted" alias="luser luser_* luser|*">
<user nick="gen" alias="gen_">
<user nick="Littlemutt" alias="Littlemutt_afk">

<user nick="fligtar" alias="fligtar|* fligtar_* fligtarrrrrrr">
<user nick="wenzel" alias="wenzel|*">
<user nick="lars" alias="lars|*">
<user nick="clouserw" alias="clouservv">

<user nick="elichak" alias="elichak_* elichak|* chak|life">
<user nick="cesar" alias="cesar[*] cesar-* cesar_* Cesar128 _cesar_">
<user nick="ctyler" alias="ctyler-* ctyler_*">
<user nick="lsblakk" alias="lsblakk_* lsblakk-*">
<user nick="armenzg" alias="armenzg* armen-linux">
<user nick="micadeyeye" alias="micadeyeye*">
<user nick="humph" alias="dave dave_with_dark_glasses dave_with_earplugs">
<user nick="Tiago" alias="Tiago|*">
<user nick="xrayon" alias="xrayon*">
<user nick="RealMarkP" alias="RealMarkP*">
<user nick="ashughes" alias="ashughes*">
<user nick="jb" alias="jb- jb_">
<user nick="marcia" alias="marcia_*">
<user nick="mfinkle" alias="mfinkle*">
<user nick="dominic" alias="dominic|study">
<user nick="inveigle" alias="inveigle*">
<user nick="eor" alias="eor_sick eor|afk eor_">
<user nick="davel" alias="davel_*">
<user nick="cozby" alias="cozby|* cozby_*">
<user nick="philly" alias="philly|* philly_*">
<user nick="sancus" alias="sancus_">
<user nick="Vanessa" alias="Vanessa_">
<user nick="pstdenis" alias="pstdenis_">
<user nick="alice" alias="alice|*">
<user nick="shaver" alias="shaver*">
<user nick="mmullin" alias="coren_aka_mullin">

<user nick="cl" alias="cl|* Blackbeard cl-* cflawson* redonkulous Raid|KillsBugsDead clawson*">
<user nick="maxr" alias="max">
<user nick="sauron" alias="ardissone* formerly-smokey smokey* MrProject MrCamino085">
<user nick="kreeger" alias="kreeger*">
<user nick="froodian" alias="froodian* ian|lastdayofinternet">
<user nick="aschulm" alias="aschulm*">
<user nick="josh" alias="josh2 josh_*">
<user nick="smorgan" alias="smorgan_*">
<user nick="delliott" alias="deliott desmond delliott*">
<user nick="peeja" alias="peeja*">
<user nick="DerekS" alias="DerekS_">
<user nick="Wevah" alias="Wevah* DreadPirateWevah">
<user nick="BDog" alias="BDog|Idle">
<user nick="julian" alias="CapnSpellcheck julian[*] spellcheck julian_">
<user nick="japser" alias="japser* jasper">
<user nick="hwaara" alias="hwaara*">
<user nick="pinkerton" alias="pinkCoffee pinkPanera piratePink">
<user nick="pnhChris" alias="pnhClosedShop">
<user nick="yama" alias="yama_mac yamac">
<user nick="mento" alias="mento`airbag">
<user nick="beniamino" alias="beniamino_">
<user nick="kfs" alias="kfs|work kfs_">
<user nick="murph" alias="seanmurph">
<user nick="BruceD" alias="BruceRD">
<user nick="Jeff" alias="jeff|WWDC">

<user nick="glob" alias="glob_work">
<user nick="cls" alias="cls_">
<user nick="LpSolit" alias="LpSolit_*">
<user nick="joel" alias="joel_lite">
<user nick="FenixRF" alias="Fenix|work">

<user nick="auenf" alias="auenf*">
<user nick="maki" alias="_RSZ_ victory rsz_x20 _RSZ__ _maki">
<user nick="justdave" alias="justdave_*">
<user nick="wicked" alias="Zornreich">
<user nick="Callek" alias="Callek_*">
<user nick="IRCMonkey" alias="IRCMonkey*">
<user nick="shadytrees" alias="hao2lian hao2lain">
<user nick="avrom" alias="AvvY* avrom* loveme4iamjesus avr0m*">
<user nick="nosebleed" alias="nosey_b">
<user nick="jX" alias="jX|* jX-* jesusX jesus_X">
<user nick="MightyMu" alias="MightyMu_*">
<user nick="wheels" alias="AdaByron AdaEngaged wheelsPromoted wheelsInCA">
<user nick="Tristor" alias="Tristor|* Tris|* Tristor2">
<user nick="Q_Continuum" alias="Q_Cont|* Q_Continuuum Q_Contoxicated Q_Confuzzled Q_intoxicated Q_Continuum_">
<user nick="Tom" alias="Tom_ Tom2 Thomas">
<user nick="sysKin" alias="sysKin_*">
<user nick="Kovu" alias="Kovu_*">
<user nick="Hendikins" alias="Hendikins|*">
<user nick="Animal" alias="Animal_ CaffeinatedCowboy">
<user nick="ct^" alias="ct^*">
<user nick="madmoose" alias="mooseEngaged">
<user nick="adiabatic" alias="adiabatty adiabonkers">
<user nick="ORenyRen" alias="Ren|Away">
<user nick="nilson" alias="nilson_osx nilson_">
<user nick="Gulanzon" alias="Gul|*">
<user nick="Caleb" alias="Caleb--">
<user nick="Kittybitch" alias="Kittybitch|* kitty|away">
<user nick="Legoguy" alias="Legoguy|L">
<user nick="Peng" alias="Peng_ Peng|CZ">
<user nick="Omnica" alias="Omnica|zZz">
<user nick="Vardyr" alias="Vardyr|*">
<user nick="mellon" alias="Zingger">
<user nick="dwitte" alias="dwitte*">
<user nick="Triona" alias="Caitriona TrionaZZZ">
<user nick="NSA" alias="`NSA` _NSA_">
<user nick="sspitzer" alias="sspitzer*">
<user nick="WizKid" alias="WizKid_">
<user nick="steve_k" alias="steve_k_*">
<user nick="topa" alias="topa_">
<user nick="sdwilsh" alias="comrade693 sdwilsh* sdw">
<user nick="mwu" alias="bluetape mwu_">
<user nick="dmose" alias="emose fmose dmose*">
<user nick="MisterSSL" alias="Mister-TLS">
<user nick="davida" alias="dascher">
<user nick="Colin" alias="Colin|AFK Colin2">
<user nick="bienvenu" alias="davidbienvenu bienvenu_">
<user nick="myk" alias="myk_">
<user nick="jay" alias="jay_zzz">
<user nick="jeremy" alias="jeremy|* linuxmigration linuxmigration_ Lieutenant_Jeremy jeremy_*">
<user nick="Asa" alias="Asa_ asadotzler">
<user nick="Hixie" alias="Hixie_* Hixie-*">
<user nick="alanjstr" alias="alanjstr|Work">
<user nick="ssieb" alias="ssieb_*">
<user nick="mrbkap" alias="mrb-away">
<user nick="Gijs" alias="HB-away Hannibal Hannibal_ Hannibal-afk Gijs_ Gijs2">
<user nick="db48x" alias="db48x*">
<user nick="crowder" alias="cr0wder shrf_crowder">
<user nick="ben" alias="ben_">
<user nick="bugs" alias="bugs_coding">
<user nick="asqueella" alias="asqueella_*">
<user nick="Adam" alias="Adam__">
<user nick="stilist" alias="stilist\away">
<user nick="mw22" alias="mw22_*">
<user nick="factoryjoe" alias="factoryjoe_">
<user nick="jag" alias="jag|*">
<user nick="taf2" alias="taf2_">
<user nick="bugbot" alias="supybot">
<user nick="deq" alias="deq_">
<user nick="thunder" alias="v_thunder">
<user nick="Silver" alias="Silver_* [Not]Silver Silver|*">
<user nick="chino" alias="chin1">
<user nick="mrtech" alias="mrtech*">
<user nick="Lawrence" alias="LawrenceAFK Lawrence2">
<user nick="wsm" alias="wsm0 WSMwk">
<user nick="mrz" alias="mrz_* mrz-*">
<user nick="robarnold" alias="rob_arnold">
<user nick="madhava" alias="madhava_">
<user nick="jcraig" alias="jcraig|away">
<user nick="koifans" alias="koifans_ koifans|away">
<user nick="kinetik" alias="kinetik_">
<user nick="awdelyea" alias="awdelyea_">
<user nick="Mitch" alias="Mitch_1_2">
<user nick="Glenjamin" alias="ReadMe">
<user nick="hagabaka" alias="hagabaka_">
<user nick="Spikor" alias="Spikor|work">
<user nick="Havvy" alias="Havvy|">
<user nick="Cork" alias="Cork[*]">

<user nick="aki" alias="aki|*">
<user nick="catlee" alias="catlee|* catlee-*">
<user nick="nagios" alias="nagios-*">
